import unittest
from unittest.mock import patch

from tools import mock_store
from tools.build_checker import check_repo_health
from tools.github_tool import GitHubConfig, GitHubClient, check_github_auth, commit_files, create_repo
from tools.repo_writer import append_build_log
from tools.verifier import verify_commit


class Person3GitHubToolTests(unittest.TestCase):
    def setUp(self):
        mock_store.reset_mock_store()

    def test_config_reads_mock_mode(self):
        with patch.dict(
            "os.environ",
            {
                "GITHUB_TOKEN": "secret-token",
                "GITHUB_OWNER": "demo-owner",
                "GITHUB_REPO_PREFIX": "mvpilot-generated-",
                "MVPILOT_MOCK_TOOLS": "true",
            },
            clear=True,
        ):
            config = GitHubConfig.from_env()

        self.assertEqual(config.token, "secret-token")
        self.assertEqual(config.owner, "demo-owner")
        self.assertTrue(config.mock_tools)

    def test_client_refuses_live_request_without_token(self):
        client = GitHubClient(GitHubConfig(token=None, owner="owner", repo_prefix="mvpilot-generated-", mock_tools=False))

        with self.assertRaises(RuntimeError):
            client.get_authenticated_user()

    def test_create_repo_uses_mock_mode_without_credentials(self):
        with patch.dict(
            "os.environ",
            {
                "GITHUB_OWNER": "demo-owner",
                "GITHUB_REPO_PREFIX": "mvpilot-generated-",
                "MVPILOT_MOCK_TOOLS": "true",
            },
            clear=True,
        ):
            result = create_repo(
                "mvpilot-generated-referral-agent",
                "Generated by MVPilot",
                "public",
            )

        self.assertEqual(result["tool_name"], "github.create_repo")
        self.assertEqual(result["status"], "mock")
        self.assertEqual(result["verification_status"], "mock")
        self.assertEqual(result["output"]["repo_name"], "mvpilot-generated-referral-agent")

    def test_check_github_auth_uses_mock_mode(self):
        with patch.dict(
            "os.environ",
            {
                "GITHUB_OWNER": "demo-owner",
                "MVPILOT_MOCK_TOOLS": "true",
            },
            clear=True,
        ):
            result = check_github_auth()

        self.assertEqual(result["tool_name"], "github.check_auth")
        self.assertEqual(result["status"], "mock")
        self.assertEqual(result["verification_status"], "mock")

    def test_check_github_auth_requires_token_in_live_mode(self):
        with patch.dict(
            "os.environ",
            {
                "GITHUB_OWNER": "demo-owner",
                "MVPILOT_MOCK_TOOLS": "false",
            },
            clear=True,
        ):
            result = check_github_auth()

        self.assertEqual(result["tool_name"], "github.check_auth")
        self.assertEqual(result["status"], "failed")
        self.assertIn("GITHUB_TOKEN", result["error"])

    def test_create_repo_refuses_non_generated_repo(self):
        with patch.dict("os.environ", {"MVPILOT_MOCK_TOOLS": "true"}, clear=True):
            result = create_repo("MVPilot", "Wrong repo", "public")

        self.assertEqual(result["status"], "refused")
        self.assertIn("mvpilot-generated-", result["error"])

    def test_create_repo_rejects_invalid_visibility(self):
        with patch.dict("os.environ", {"MVPILOT_MOCK_TOOLS": "true"}, clear=True):
            result = create_repo("mvpilot-generated-demo", "Demo", "internal")

        self.assertEqual(result["status"], "failed")
        self.assertIn("validation_error", result["output"])

    def test_commit_files_uses_mock_mode(self):
        with patch.dict(
            "os.environ",
            {
                "GITHUB_OWNER": "demo-owner",
                "MVPILOT_MOCK_TOOLS": "true",
            },
            clear=True,
        ):
            result = commit_files(
                "mvpilot-generated-referral-agent",
                [
                    {"path": "README.md", "content": "# Demo"},
                    {"path": "logs/build_log.md", "content": "Started"},
                ],
                "Add initial scaffold",
            )

        self.assertEqual(result["tool_name"], "github.commit_files")
        self.assertEqual(result["status"], "mock")
        self.assertEqual(result["verification_status"], "mock")
        self.assertEqual(result["output"]["files_changed"], 2)
        self.assertEqual(result["output"]["changed_files"], ["README.md", "logs/build_log.md"])

    def test_commit_files_rejects_empty_file_list(self):
        with patch.dict("os.environ", {"MVPILOT_MOCK_TOOLS": "true"}, clear=True):
            result = commit_files("mvpilot-generated-demo", [], "Empty commit")

        self.assertEqual(result["status"], "failed")
        self.assertIn("validation_error", result["output"])

    def test_commit_files_rejects_unsafe_path(self):
        with patch.dict("os.environ", {"MVPILOT_MOCK_TOOLS": "true"}, clear=True):
            result = commit_files(
                "mvpilot-generated-demo",
                [{"path": "../secret.txt", "content": "bad"}],
                "Bad commit",
            )

        self.assertEqual(result["status"], "failed")
        self.assertIn("validation_error", result["output"])

    def test_verify_commit_accepts_mock_sha(self):
        with patch.dict("os.environ", {"MVPILOT_MOCK_TOOLS": "true"}, clear=True):
            commit_result = commit_files(
                "mvpilot-generated-demo",
                [{"path": "README.md", "content": "# Demo"}],
                "Add README",
            )
            result = verify_commit("mvpilot-generated-demo", commit_result["output"]["commit_sha"])

        self.assertEqual(result["tool_name"], "github.verify_commit")
        self.assertEqual(result["status"], "mock")
        self.assertTrue(result["output"]["verified"])
        self.assertEqual(result["output"]["files_changed"], ["README.md"])

    def test_verify_commit_rejects_fake_live_shape_in_mock_mode(self):
        with patch.dict("os.environ", {"MVPILOT_MOCK_TOOLS": "true"}, clear=True):
            result = verify_commit("mvpilot-generated-demo", "abc123")

        self.assertEqual(result["status"], "failed")
        self.assertEqual(result["verification_status"], "failed")

    def test_verify_commit_rejects_empty_sha(self):
        with patch.dict("os.environ", {"MVPILOT_MOCK_TOOLS": "true"}, clear=True):
            result = verify_commit("mvpilot-generated-demo", " ")

        self.assertEqual(result["status"], "failed")
        self.assertIn("must not be empty", result["error"])

    def test_append_build_log_preserves_previous_entries(self):
        with patch.dict("os.environ", {"MVPILOT_MOCK_TOOLS": "true"}, clear=True):
            first = append_build_log("task-1", "mvpilot-generated-demo", "Created repo", {"step": 1})
            second = append_build_log("task-1", "mvpilot-generated-demo", "Committed files", {"step": 2})
            content = mock_store.get_file("mvpilot-generated-demo", "logs/build_log.md")

        self.assertEqual(first["status"], "mock")
        self.assertEqual(second["status"], "mock")
        self.assertIn("Created repo", content)
        self.assertIn("Committed files", content)

    def test_append_build_log_rejects_empty_message(self):
        with patch.dict("os.environ", {"MVPILOT_MOCK_TOOLS": "true"}, clear=True):
            result = append_build_log("task-1", "mvpilot-generated-demo", " ", {})

        self.assertEqual(result["status"], "failed")
        self.assertIn("message must not be empty", result["error"])

    def test_append_build_log_retries_once_on_live_commit_failure(self):
        with (
            patch.dict("os.environ", {"MVPILOT_MOCK_TOOLS": "false", "GITHUB_TOKEN": "token", "GITHUB_OWNER": "owner"}, clear=True),
            patch("tools.repo_writer.GitHubClient") as client_class,
            patch("tools.repo_writer.commit_files") as commit_files_mock,
            patch("tools.repo_writer._format_log_entry", return_value="- fixed | task=task-1 | Committed files\n"),
        ):
            client = client_class.return_value
            client.get_file_text.return_value = "# MVPilot Build Log\n\n"
            commit_files_mock.side_effect = [
                {
                    "tool_name": "github.commit_files",
                    "status": "failed",
                    "verification_status": "failed",
                    "output": {},
                    "error": "simulated conflict",
                },
                {
                    "tool_name": "github.commit_files",
                    "status": "success",
                    "verification_status": "verified",
                    "output": {"commit_sha": "abc123"},
                    "error": None,
                },
            ]
            client.get_file_text.side_effect = [
                "# MVPilot Build Log\n\n",
                "# MVPilot Build Log\n\n",
                "# MVPilot Build Log\n\n- fixed | task=task-1 | Committed files\n",
            ]

            result = append_build_log("task-1", "mvpilot-generated-demo", "Committed files", {})

        self.assertEqual(result["status"], "success")
        self.assertEqual(result["output"]["attempts"], 2)
        self.assertEqual(commit_files_mock.call_count, 2)

    def test_append_build_log_polls_after_live_commit_before_failing_verification(self):
        with (
            patch.dict("os.environ", {"MVPILOT_MOCK_TOOLS": "false", "GITHUB_TOKEN": "token", "GITHUB_OWNER": "owner"}, clear=True),
            patch("tools.repo_writer.GitHubClient") as client_class,
            patch("tools.repo_writer.commit_files") as commit_files_mock,
            patch("tools.repo_writer.sleep") as sleep_mock,
            patch("tools.repo_writer._format_log_entry", return_value="- fixed | task=task-1 | Committed files\n"),
        ):
            client = client_class.return_value
            commit_files_mock.return_value = {
                "tool_name": "github.commit_files",
                "status": "success",
                "verification_status": "verified",
                "output": {"commit_sha": "abc123"},
                "error": None,
            }
            client.get_file_text.side_effect = [
                "# MVPilot Build Log\n\n",
                "# MVPilot Build Log\n\n",
                "# MVPilot Build Log\n\n- fixed | task=task-1 | Committed files\n",
            ]

            result = append_build_log("task-1", "mvpilot-generated-demo", "Committed files", {})

        self.assertEqual(result["status"], "success")
        self.assertEqual(result["output"]["attempts"], 1)
        self.assertEqual(result["output"]["verification_attempts"], 2)
        self.assertEqual(commit_files_mock.call_count, 1)
        sleep_mock.assert_called_once()

    def test_append_build_log_accepts_verified_commit_when_contents_api_lags(self):
        with (
            patch.dict("os.environ", {"MVPILOT_MOCK_TOOLS": "false", "GITHUB_TOKEN": "token", "GITHUB_OWNER": "owner"}, clear=True),
            patch("tools.repo_writer.GitHubClient") as client_class,
            patch("tools.repo_writer.commit_files") as commit_files_mock,
            patch("tools.repo_writer.verify_commit") as verify_commit_mock,
            patch("tools.repo_writer.sleep"),
            patch("tools.repo_writer._format_log_entry", return_value="- fixed | task=task-1 | Committed files\n"),
        ):
            client = client_class.return_value
            commit_files_mock.return_value = {
                "tool_name": "github.commit_files",
                "status": "success",
                "verification_status": "verified",
                "output": {"commit_sha": "abc123"},
                "error": None,
            }
            client.get_file_text.return_value = "# MVPilot Build Log\n\n"
            verify_commit_mock.return_value = {
                "tool_name": "github.verify_commit",
                "status": "success",
                "verification_status": "verified",
                "output": {"commit_sha": "abc123", "files_changed": ["logs/build_log.md"]},
                "error": None,
            }

            result = append_build_log("task-1", "mvpilot-generated-demo", "Committed files", {})

        self.assertEqual(result["status"], "success")
        self.assertTrue(result["output"]["verified"])
        self.assertFalse(result["output"]["content_verified"])
        self.assertTrue(result["output"]["commit_verified"])
        self.assertEqual(result["output"]["verification_method"], "commit")

    def test_repo_health_passes_for_complete_mock_repo(self):
        with patch.dict("os.environ", {"MVPILOT_MOCK_TOOLS": "true"}, clear=True):
            commit_files(
                "mvpilot-generated-demo",
                [
                    {"path": "README.md", "content": "# Demo"},
                    {"path": "logs/build_log.md", "content": "# Log"},
                    {"path": "demo/demo_script.md", "content": "Demo"},
                    {"path": "requirements.txt", "content": "pydantic"},
                    {"path": "src/main.py", "content": "print('hi')"},
                ],
                "Add complete scaffold",
            )
            result = check_repo_health("mvpilot-generated-demo")

        self.assertEqual(result["status"], "mock")
        self.assertTrue(result["output"]["healthy"])

    def test_repo_health_reports_missing_files(self):
        with patch.dict("os.environ", {"MVPILOT_MOCK_TOOLS": "true"}, clear=True):
            commit_files(
                "mvpilot-generated-demo",
                [{"path": "README.md", "content": "# Demo"}],
                "Add partial scaffold",
            )
            result = check_repo_health("mvpilot-generated-demo")

        self.assertEqual(result["status"], "failed")
        self.assertFalse(result["output"]["healthy"])
        self.assertIn("logs/build_log.md exists", result["output"]["missing"])


if __name__ == "__main__":
    unittest.main()
